name: Release

on:
  release:
    types: [published]

jobs:
  push_to_registry:
    name: Test and build docker
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2

      - name: Check out code
        uses: actions/checkout@v2

      - name: Build
        run: go build -v .

      - name: Test
        run: go test -v .

      - name: Push to GitHub Packages
        uses: docker/build-push-action@v4
        with:
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
          registry: docker.pkg.github.com
          repository: duyet/applause-btn/applause-btn
          tag_with_ref: true
